# Generated by Django 2.2.1 on 2019-10-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_password', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profile_pics'),
        ),
    ]
